name: k2p_openwrt

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  BRANCH_TAG: v21.02.1
  SYSTEM: openwrt
  MODEL: k2p

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: build-system setup
      run: |
        sudo apt-get update
        sudo apt-get install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev 
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: clone repository
      run: git clone $REPO_URL -b $BRANCH_TAG openwrt

    - name: load configs
      run: cp -rf open-wrt/openwrt/include ./openwrt/

    - name: update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: install feeds
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: load .config
      run: cp -rf open-wrt/openwrt/.config ./openwrt/

    - name: make defconfig
      run: |
        cd openwrt
        make defconfig

    - name: pre-download dependencies
      run: |
        cd openwrt
        make download -j8

    - name: building images
      run: |
        cd openwrt
        make -j$(nproc)
        echo "BULID_TIME=$(date +"%m%d%H%M")" >> $GITHUB_ENV

    - name: remove packages
      if: ${{ github.event_name != 'release' && success() }}
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: upload images
      if: ${{ github.event_name != 'release' && success() }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SYSTEM }}_${{ env.MODEL }}_${{ env.BULID_TIME }}
        path: ${{ env.FIRMWARE }}
